/*eliminar todo*/

DROP TABLE IF EXISTS Profesion CASCADE;
DROP TABLE IF EXISTS Pais CASCADE;
DROP TABLE IF EXISTS Puesto CASCADE;
DROP TABLE IF EXISTS Departamento CASCADE;
DROP TABLE IF EXISTS Miembro CASCADE;
DROP TABLE IF EXISTS Puesto_Miembro CASCADE;
DROP TABLE IF EXISTS Tipo_Medalla CASCADE;
DROP TABLE IF EXISTS Medallero CASCADE;
DROP TABLE IF EXISTS Disciplina CASCADE;
DROP TABLE IF EXISTS Atleta CASCADE;
DROP TABLE IF EXISTS Categoria CASCADE;
DROP TABLE IF EXISTS Tipo_Participacion CASCADE;
DROP TABLE IF EXISTS Evento CASCADE;
DROP TABLE IF EXISTS Evento_Atleta CASCADE;
DROP TABLE IF EXISTS Televisora CASCADE;
DROP TABLE IF EXISTS Costo_Evento CASCADE;
DROP TABLE IF EXISTS Disciplina_Atleta CASCADE;
DROP TABLE IF EXISTS Sede CASCADE;
